version: 0.2
env:
  variables:
    NODE_ENV: "production"
phases:
  install:
    commands:
      -  #n 17
      - node -v
      - npm install -g next
      - npm install -g typescript
      - codebuild-breakpoint
      - yarn
  build:
    commands:
      - yarn build
artifacts:
  files:
    - .next/**/*
    - package.json
    - next.config.js
    - tsconfig.json
