version: 0.2
env:
  variables:
    NODE_ENV: "production"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 17
      - node -v
      - npm cache clean --force
      - rm -rf node_modules
      - npm ci
      - npm list
      - npm list -g
      -  #npm install -g next
      -  #npm install -g typescript
      -  #yarn add --dev typescript @types/node
  build:
    commands:
      - yarn build
artifacts:
  files:
    - .next/**/*
    - package.json
    - next.config.js
    - tsconfig.json
