version: 0.2
env:
  variables:
    NODE_ENV: "production"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 17
      - node -v
      - yarn cache clean
      - rm -rf node_modules
      - yarn
      - yarn add --dev typescript@4.6.3 @types/node@17.0.23 @types/react-dom@17.0.14
      - yarn add --dev @types/gtag.js@^0.0.10
      - yarn add --dev eslint@8.12.0 eslint-config-next@12.1.1
      - yarn add --dev typescript@4.6.3
      -  #npm install -g next
      -  #npm install -g typescript
      -  #yarn add --dev typescript @types/node
  build:
    commands:
      - yarn build
artifacts:
  files:
    - .next/**/*
    - package.json
    - next.config.js
    - tsconfig.json
