version: 0.2
env:
  variables:
    NODE_ENV: "production"
phases:
  install:
    commands:
      -  #n 17
      - node -v
      - codebuild-breakpoint
      - npm install -g next
      - npm install -g typescript
      - npm i
  build:
    commands:
      - npx next build && next export
artifacts:
  files:
    - .next/**/*
    - package.json
    - next.config.js
    - tsconfig.json
